version: '3'
services:
 db:
  image: mysql
  environment:
   MYSQL_ROOT_PASSWORD: password
   MYSQL_PASSWORD: password
   MYSQL_DATABASE: CloudMatrixTool
  volumes:
   - db_data:/var/lib/mysql
  healthcheck:
   test: '/usr/bin/mysql --user=root --password=password --execute="SHOW DATABASES;"'
   interval: 2s
   timeout: 20s
   retries: 3
 web:
  image: leemacabuhay/team5:app.v1
  ports:
    - 8080:8080 
  depends_on:
    - db
volumes:
  db_data:
